///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class AnimeDetailModelVoiceActorsPersonImagesJpg {
/*
{
  "image_url": "https://cdn.myanimelist.net/images/voiceactors/3/70398.jpg?s=01ab90c96ed2a89ebc025b02d8c38893"
} 
*/

  String? imageUrl;

  AnimeDetailModelVoiceActorsPersonImagesJpg({
    this.imageUrl,
  });
  AnimeDetailModelVoiceActorsPersonImagesJpg.fromJson(Map<String, dynamic> json) {
    imageUrl = json['image_url']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['image_url'] = imageUrl;
    return data;
  }
}

class AnimeDetailModelVoiceActorsPersonImages {
/*
{
  "jpg": {
    "image_url": "https://cdn.myanimelist.net/images/voiceactors/3/70398.jpg?s=01ab90c96ed2a89ebc025b02d8c38893"
  }
} 
*/

  AnimeDetailModelVoiceActorsPersonImagesJpg? jpg;

  AnimeDetailModelVoiceActorsPersonImages({
    this.jpg,
  });
  AnimeDetailModelVoiceActorsPersonImages.fromJson(Map<String, dynamic> json) {
    jpg = (json['jpg'] != null) ? AnimeDetailModelVoiceActorsPersonImagesJpg.fromJson(json['jpg']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (jpg != null) {
      data['jpg'] = jpg!.toJson();
    }
    return data;
  }
}

class AnimeDetailModelVoiceActorsPerson {
/*
{
  "mal_id": 47097,
  "url": "https://myanimelist.net/people/47097/Kana_Ichinose",
  "images": {
    "jpg": {
      "image_url": "https://cdn.myanimelist.net/images/voiceactors/3/70398.jpg?s=01ab90c96ed2a89ebc025b02d8c38893"
    }
  },
  "name": "Ichinose, Kana"
} 
*/

  int? malId;
  String? url;
  AnimeDetailModelVoiceActorsPersonImages? images;
  String? name;

  AnimeDetailModelVoiceActorsPerson({
    this.malId,
    this.url,
    this.images,
    this.name,
  });
  AnimeDetailModelVoiceActorsPerson.fromJson(Map<String, dynamic> json) {
    malId = json['mal_id']?.toInt();
    url = json['url']?.toString();
    images = (json['images'] != null) ? AnimeDetailModelVoiceActorsPersonImages.fromJson(json['images']) : null;
    name = json['name']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['mal_id'] = malId;
    data['url'] = url;
    if (images != null) {
      data['images'] = images!.toJson();
    }
    data['name'] = name;
    return data;
  }
}

class AnimeDetailModelVoiceActors {
/*
{
  "person": {
    "mal_id": 47097,
    "url": "https://myanimelist.net/people/47097/Kana_Ichinose",
    "images": {
      "jpg": {
        "image_url": "https://cdn.myanimelist.net/images/voiceactors/3/70398.jpg?s=01ab90c96ed2a89ebc025b02d8c38893"
      }
    },
    "name": "Ichinose, Kana"
  },
  "language": "Japanese"
} 
*/

  AnimeDetailModelVoiceActorsPerson? person;
  String? language;

  AnimeDetailModelVoiceActors({
    this.person,
    this.language,
  });
  AnimeDetailModelVoiceActors.fromJson(Map<String, dynamic> json) {
    person = (json['person'] != null) ? AnimeDetailModelVoiceActorsPerson.fromJson(json['person']) : null;
    language = json['language']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (person != null) {
      data['person'] = person!.toJson();
    }
    data['language'] = language;
    return data;
  }
}

class AnimeDetailModelCharacterImagesWebp {
/*
{
  "image_url": "https://cdn.myanimelist.net/images/characters/13/519083.webp?s=b280b410b588ebcd3fd30ac6fad02978",
  "small_image_url": "https://cdn.myanimelist.net/images/characters/13/519083t.webp?s=b280b410b588ebcd3fd30ac6fad02978"
} 
*/

  String? imageUrl;
  String? smallImageUrl;

  AnimeDetailModelCharacterImagesWebp({
    this.imageUrl,
    this.smallImageUrl,
  });
  AnimeDetailModelCharacterImagesWebp.fromJson(Map<String, dynamic> json) {
    imageUrl = json['image_url']?.toString();
    smallImageUrl = json['small_image_url']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['image_url'] = imageUrl;
    data['small_image_url'] = smallImageUrl;
    return data;
  }
}

class AnimeDetailModelCharacterImagesJpg {
/*
{
  "image_url": "https://cdn.myanimelist.net/images/characters/13/519083.jpg?s=b280b410b588ebcd3fd30ac6fad02978"
} 
*/

  String? imageUrl;

  AnimeDetailModelCharacterImagesJpg({
    this.imageUrl,
  });
  AnimeDetailModelCharacterImagesJpg.fromJson(Map<String, dynamic> json) {
    imageUrl = json['image_url']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['image_url'] = imageUrl;
    return data;
  }
}

class AnimeDetailModelCharacterImages {
/*
{
  "jpg": {
    "image_url": "https://cdn.myanimelist.net/images/characters/13/519083.jpg?s=b280b410b588ebcd3fd30ac6fad02978"
  },
  "webp": {
    "image_url": "https://cdn.myanimelist.net/images/characters/13/519083.webp?s=b280b410b588ebcd3fd30ac6fad02978",
    "small_image_url": "https://cdn.myanimelist.net/images/characters/13/519083t.webp?s=b280b410b588ebcd3fd30ac6fad02978"
  }
} 
*/

  AnimeDetailModelCharacterImagesJpg? jpg;
  AnimeDetailModelCharacterImagesWebp? webp;

  AnimeDetailModelCharacterImages({
    this.jpg,
    this.webp,
  });
  AnimeDetailModelCharacterImages.fromJson(Map<String, dynamic> json) {
    jpg = (json['jpg'] != null) ? AnimeDetailModelCharacterImagesJpg.fromJson(json['jpg']) : null;
    webp = (json['webp'] != null) ? AnimeDetailModelCharacterImagesWebp.fromJson(json['webp']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (jpg != null) {
      data['jpg'] = jpg!.toJson();
    }
    if (webp != null) {
      data['webp'] = webp!.toJson();
    }
    return data;
  }
}

class AnimeDetailModelCharacter {
/*
{
  "mal_id": 188176,
  "url": "https://myanimelist.net/character/188176/Fern",
  "images": {
    "jpg": {
      "image_url": "https://cdn.myanimelist.net/images/characters/13/519083.jpg?s=b280b410b588ebcd3fd30ac6fad02978"
    },
    "webp": {
      "image_url": "https://cdn.myanimelist.net/images/characters/13/519083.webp?s=b280b410b588ebcd3fd30ac6fad02978",
      "small_image_url": "https://cdn.myanimelist.net/images/characters/13/519083t.webp?s=b280b410b588ebcd3fd30ac6fad02978"
    }
  },
  "name": "Fern"
} 
*/

  int? malId;
  String? url;
  AnimeDetailModelCharacterImages? images;
  String? name;

  AnimeDetailModelCharacter({
    this.malId,
    this.url,
    this.images,
    this.name,
  });
  AnimeDetailModelCharacter.fromJson(Map<String, dynamic> json) {
    malId = json['mal_id']?.toInt();
    url = json['url']?.toString();
    images = (json['images'] != null) ? AnimeDetailModelCharacterImages.fromJson(json['images']) : null;
    name = json['name']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['mal_id'] = malId;
    data['url'] = url;
    if (images != null) {
      data['images'] = images!.toJson();
    }
    data['name'] = name;
    return data;
  }
}

class AnimeDetailModel {
/*
{
  "character": {
    "mal_id": 188176,
    "url": "https://myanimelist.net/character/188176/Fern",
    "images": {
      "jpg": {
        "image_url": "https://cdn.myanimelist.net/images/characters/13/519083.jpg?s=b280b410b588ebcd3fd30ac6fad02978"
      },
      "webp": {
        "image_url": "https://cdn.myanimelist.net/images/characters/13/519083.webp?s=b280b410b588ebcd3fd30ac6fad02978",
        "small_image_url": "https://cdn.myanimelist.net/images/characters/13/519083t.webp?s=b280b410b588ebcd3fd30ac6fad02978"
      }
    },
    "name": "Fern"
  },
  "role": "Main",
  "favorites": 2927,
  "voice_actors": [
    {
      "person": {
        "mal_id": 47097,
        "url": "https://myanimelist.net/people/47097/Kana_Ichinose",
        "images": {
          "jpg": {
            "image_url": "https://cdn.myanimelist.net/images/voiceactors/3/70398.jpg?s=01ab90c96ed2a89ebc025b02d8c38893"
          }
        },
        "name": "Ichinose, Kana"
      },
      "language": "Japanese"
    }
  ]
} 
*/

  AnimeDetailModelCharacter? character;
  String? role;
  int? favorites;
  List<AnimeDetailModelVoiceActors?>? voiceActors;

  AnimeDetailModel({
    this.character,
    this.role,
    this.favorites,
    this.voiceActors,
  });
  AnimeDetailModel.fromJson(Map<String, dynamic> json) {
    character = (json['character'] != null) ? AnimeDetailModelCharacter.fromJson(json['character']) : null;
    role = json['role']?.toString();
    favorites = json['favorites']?.toInt();
  if (json['voice_actors'] != null) {
  final v = json['voice_actors'];
  final arr0 = <AnimeDetailModelVoiceActors>[];
  v.forEach((v) {
  arr0.add(AnimeDetailModelVoiceActors.fromJson(v));
  });
    voiceActors = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (character != null) {
      data['character'] = character!.toJson();
    }
    data['role'] = role;
    data['favorites'] = favorites;
    if (voiceActors != null) {
      final v = voiceActors;
      final arr0 = [];
  v!.forEach((v) {
  arr0.add(v!.toJson());
  });
      data['voice_actors'] = arr0;
    }
    return data;
  }
}
