///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class AnimePaginationModelItems {
  int? count;
  int? total;
  int? perPage;

  AnimePaginationModelItems({
    this.count,
    this.total,
    this.perPage,
  });
  AnimePaginationModelItems.fromJson(Map<String, dynamic> json) {
    count = json['count']?.toInt();
    total = json['total']?.toInt();
    perPage = json['per_page']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['count'] = count;
    data['total'] = total;
    data['per_page'] = perPage;
    return data;
  }
}

class AnimePaginationModel {
  int? lastVisiblePage;
  bool? hasNextPage;
  int? currentPage;
  AnimePaginationModelItems? items;

  AnimePaginationModel({
    this.lastVisiblePage,
    this.hasNextPage,
    this.currentPage,
    this.items,
  });
  AnimePaginationModel.fromJson(Map<String, dynamic> json) {
    lastVisiblePage = json['last_visible_page']?.toInt();
    hasNextPage = json['has_next_page'];
    currentPage = json['current_page']?.toInt();
    items = (json['items'] != null)
        ? AnimePaginationModelItems.fromJson(json['items'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['last_visible_page'] = lastVisiblePage;
    data['has_next_page'] = hasNextPage;
    data['current_page'] = currentPage;
    if (items != null) {
      data['items'] = items!.toJson();
    }
    return data;
  }
}
